- name: Upload docker to rpi
  synchronize:
    src: ../docker/
    dest: ~/CodePlayerBox/docker-ap-rpi/
    rsync_opts:
      - "--delete"
      - "--exclude=script"
      - "--exclude=.DS_Store"

- name: Upload script to rpi
  synchronize:
    src: ../script/
    dest: ~/CodePlayerBox/docker-ap-rpi/script/
    rsync_opts:
      - "--delete"
      - "--exclude=.DS_Store"
